[[tests]]
name = "add host name to log output"

[[tests.inputs]]
insert_at = "add_agent_hostname"
type = "log"

[tests.inputs.log_fields]
message = '{"bytes":6301,"host":"127.0.0.1","method":"GET"}'

[[tests.outputs]]
extract_from = "add_agent_hostname"

[[tests.outputs.conditions]]
type = "vrl"
source = '''
assert!(exists(.agent_hostname))
assert_eq!(.agent_hostname, "test-env")
'''
